### ISSUE TITLE
I think that it should use the hardware encoder and decoder.

### ISSUE THREAD

**Issue by SetoKaiba** [because-why-not/uwebrtc_visionpro_testproj#1]
https://github.com/because-why-not/com.unity.webrtc_visionpro/blob/main_xros_test/Plugin~/WebRTCPlugin/PlatformBase.h#L23-L31
According to this code, the UNITY_OSX is not defined.
https://github.com/because-why-not/com.unity.webrtc_visionpro/blob/main_xros_test/Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.cpp#L39-L41
According to this code, it won't use hardware decoder and encoder in video toolbox.

Maybe add a macro here?

**Comment by devluz** [comment]
When porting the underlaying libwebrtc the hardware codecs didn't compile and later caused runtime crashes when the framework is loaded.
I think those crashes are fixed but there is still a risk you run into problems with it. I suspect it will max out at 720p.
I create a test build if you want to try: see branch [v0.0.1_release_hwcodecs](https://github.com/because-why-not/uwebrtc_visionpro_testproj/tree/v0.0.1_release_hwcodecs)

**Comment by SetoKaiba** [comment]
> When porting the underlaying libwebrtc the hardware codecs didn't compile and later caused runtime crashes when the framework is loaded. I think those crashes are fixed but there is still a risk you run into problems with it. I suspect it will max out at 720p. I create a test build if you want to try: see branch [v0.0.1_release_hwcodecs](https://github.com/because-why-not/uwebrtc_visionpro_testproj/tree/v0.0.1_release_hwcodecs)

How is it fixed? Could you please upload that branch for com.unity.webrtc_visionpro as well? Thank you.

**Comment by devluz** [comment]
I really just added UNITY_VISIONOS and uploaded the rebuild for testing. I have no way of testing this myself.  https://github.com/because-why-not/com.unity.webrtc_visionpro/tree/xros_hwcodecs

I have uploaded my workspace I use to build everything: https://github.com/because-why-not/uwebrtc_visionpro
This will build com.unity.webrtc but with the custom [webrtc_visionpro](https://github.com/because-why-not/webrtc_visionpro) build.

**Comment by devluz** [comment]
I include it as default in future versions now
